
export default function Home() {
  return (
    <div>I am Home Page</div>
  );
}

// HUMNE EK ABOUT FOLDER AUR CONTACT FOLDER ME PAGE.JS BANAYA HAI AGAR HUM APNE LOCAL HOST / KE BAAD APNE FOLDER KA NAAM DALENGE TO USS FOLDER ME KA APNA PAGE RUN HOGA

// AUR NAVBAR HUMHE APNE HARR PAGE ME CHAHIYE TO USSE HUM FIRST-APP FOLDER ME COMPONENTS FOLDER KE ANDER LIKHENGE AUR USKE BAAD USSE APNE LAYOUT.JS ME REACT JAISE IMPORT KAR LENGE JISSE VO CHALEGA HARR PAGE ME